%YAML:1.0
---
# The modifications of the output file from Kalibr:
# 1. For each matrix (e.g. cam0/T_cam_imu), remove the brackets and minus sign for each line. Use one pair of brackets for each matrix.
# 2. Add the T_imu_body at the end of the calibration file (usually set to identity).
global:
  max_cam_state_size : 20
  position_std_threshold : 8.0
  rotation_threshold : 0.2618
  translation_threshold : 0.4
  tracking_rate_threshold : 0.5
feature:
      translation_threshold : -1.0
noise:
   gyro : 0.005
   acc  : 0.05
   gyro_bias : 0.001
   acc_bias  : 0.01
   feature   : 0.035
initial_state_velocity :
      x : 0.0
      y : 0.0
      z : 0.0
initial_covariance :
    velocity : 0.25
    gyro_bias: 0.01
    acc_bias : 0.01
    extrinsic_rotation_cov   : 3.0462e-4
    extrinsic_translation_cov: 2.5e-5

image_processor:
   grid_row : 4
   grid_col : 5
   grid_min_feature_num : 3
   grid_max_feature_num : 4
   pyramid_levels : 3
   patch_size     : 15
   fast_threshold : 10
   max_iteration  : 30
   track_precision: 0.01
   ransac_threshold : 3
   stereo_threshold : 5
